name: 'Action Platform'
description: 'A GitHub Action that provides access to the platform.sh CLI'
author: 'Adam Cooper'
branding:
  icon: 'upload-cloud'
  color: 'blue'
inputs:
  token: 
    description: 'Your platform.sh API token https://docs.platform.sh/development/cli/api-tokens.html'
    required: true
  version:
    description: 'The version of the CLI to install, defaults to latest'
    required: false
    default: 'latest'
runs:
  using: 'node16'
  main: 'dist/index.js'
